import streamlit as st
import requests
import datetime

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="🥐 AI Bakery Visit Planner",
    page_icon="🥐",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🥐 AI Bakery Visit Planner")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("Which bakery in Germany would you like to explore today?")

# Chat input box
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Find me the best croissant bakery in Berlin")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # Show spinner while waiting for backend
        with st.spinner("AI Bakery Planner is curating your experience..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# 🥐 AI Bakery Visit Plan

**🕒 Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**📍 Created by:** AI Bakery Visit Planner  

---

{answer}

---

*This bakery visit plan was generated by AI. Please verify all timings, costs, and availability before your visit.*
"""
            st.markdown(markdown_content)
        else:
            st.error("The AI Bakery Planner failed to respond: " + response.text)

    except Exception as e:
        st.error(f"The response failed due to: {e}")
